import { createOpenAPI } from "fumadocs-openapi/server";
import type { Document } from "fumadocs-openapi";
// Generated by scripts/build-openapi-json.mts (predev/prebuild) from the source-of-truth YAML
// below — imported as a real JS object so no runtime file read happens in the built app. Needed
// on Cloudflare Workers specifically: passing the .yaml path as `input` instead reads it via
// Node's fs at request time, which doesn't exist in the Workers isolate (confirmed: `[OpenAPI]
// Failed to resolve input` under `wrangler dev` against the real .open-next build).
import doc from "../openapi/cortex-api.json";

// Source of truth: openapi/cortex-api.yaml, hand-written against the actual cortex-backend
// Starlette routes (task 0082) — cortex-backend has no framework that auto-generates one. The
// key below must stay "./openapi/cortex-api.yaml" — it's what generated pages under
// content/docs/api-reference/endpoints/** reference via their `document` prop.
export const openapi = createOpenAPI({
  input: { "./openapi/cortex-api.yaml": doc as unknown as Document },
});
