import { source } from '@/lib/source';
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
  MarkdownCopyButton,
  ViewOptionsPopover,
} from 'fumadocs-ui/layouts/docs/page';
import { notFound } from 'next/navigation';
import { getMDXComponents } from '@/components/mdx';
import type { Metadata } from 'next';
import type { MDXComponents } from 'mdx/types';
import { createRelativeLink } from 'fumadocs-ui/mdx';
import { getPageImageUrl, getPageMarkdownUrl, gitConfig } from '@/lib/shared';
import { openapi } from '@/lib/openapi';
import { OpenAPIPage } from '@/components/openapi-page';
import type { GeneratedPageProps } from 'fumadocs-openapi';

function PreloadedOpenAPIPage(
  preloaded: Awaited<ReturnType<typeof openapi.preloadOpenAPIPage>>['preloaded']
) {
  function Bound(p: GeneratedPageProps) {
    return <OpenAPIPage preloaded={preloaded} {...p} />;
  }
  Bound.displayName = 'PreloadedOpenAPIPage';
  return Bound;
}

export default async function Page(props: PageProps<'/docs/[[...slug]]'>) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;
  const markdownUrl = getPageMarkdownUrl(page).url;

  // Pages generated by scripts/generate-docs.mts declare `_openapi` in frontmatter and render
  // an `<OpenAPIPage document="..." operations={...} />` that needs the schema preloaded and
  // handed to it server-side (fumadocs-openapi doesn't fetch `document` client-side) — bind a
  // page-specific OpenAPIPage carrying that preload, overriding the plain one in getMDXComponents.
  const extraComponents: MDXComponents = {
    // this allows you to link to other pages with relative file paths
    a: createRelativeLink(source, page),
  };
  if (page.data._openapi) {
    const { preloaded } = await openapi.preloadOpenAPIPage(page);
    extraComponents.OpenAPIPage = PreloadedOpenAPIPage(preloaded);
  }

  return (
    <DocsPage toc={page.data.toc} full={page.data.full}>
      <DocsTitle>{page.data.title}</DocsTitle>
      <DocsDescription className="mb-0">{page.data.description}</DocsDescription>
      <div className="flex flex-row gap-2 items-center border-b pb-6">
        <MarkdownCopyButton markdownUrl={markdownUrl} />
        <ViewOptionsPopover
          markdownUrl={markdownUrl}
          githubUrl={`https://github.com/${gitConfig.user}/${gitConfig.repo}/blob/${gitConfig.branch}/content/docs/${page.path}`}
        />
      </div>
      <DocsBody>
        <MDX components={getMDXComponents(extraComponents)} />
      </DocsBody>
    </DocsPage>
  );
}

export async function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(props: PageProps<'/docs/[[...slug]]'>): Promise<Metadata> {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  return {
    title: page.data.title,
    description: page.data.description,
    openGraph: {
      images: getPageImageUrl(page).url,
    },
  };
}
